-- ========================================================
-- FUELGO SUPABASE DATABASE SETUP SCRIPT
-- Copy & Paste this entire script into your Supabase SQL Editor
-- URL: https://supabase.com/dashboard/project/feshnblvfdhjvgehklvd/sql
-- ========================================================

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT,
  phone TEXT,
  google_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Fuel Prices Table
CREATE TABLE IF NOT EXISTS public.fuel_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fuel_type TEXT UNIQUE NOT NULL,
  price_per_unit NUMERIC(10, 2) NOT NULL,
  unit TEXT NOT NULL,
  change_pct NUMERIC(5, 2) DEFAULT 0.00,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Gas Stations Table
CREATE TABLE IF NOT EXISTS public.stations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  emoji TEXT DEFAULT '⛽',
  city TEXT NOT NULL DEFAULT 'Chennai',
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  rating NUMERIC(3, 1) DEFAULT 4.5,
  is_open BOOLEAN DEFAULT TRUE,
  fuels_available JSONB DEFAULT '["petrol", "diesel"]'::jsonb,
  distance_km NUMERIC(5, 2) DEFAULT 1.0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Fuel Orders & Live GPS Tracking Table
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  station_id BIGINT REFERENCES public.stations(id) ON DELETE SET NULL,
  fuel_type TEXT NOT NULL,
  quantity_litres NUMERIC(10, 2) NOT NULL,
  total_price NUMERIC(10, 2) NOT NULL,
  payment_method TEXT NOT NULL,
  delivery_address TEXT DEFAULT 'Chetipedu, Tamil Nadu — 602105',
  delivery_lat DOUBLE PRECISION DEFAULT 12.9734,
  delivery_lng DOUBLE PRECISION DEFAULT 79.9328,
  agent_name TEXT DEFAULT 'Ravi Kumar',
  agent_phone TEXT DEFAULT '9876500402',
  agent_lat DOUBLE PRECISION DEFAULT 12.9760,
  agent_lng DOUBLE PRECISION DEFAULT 79.9360,
  status TEXT DEFAULT 'confirmed',
  eta_minutes INTEGER DEFAULT 20,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ========================================================
-- ENABLE ROW LEVEL SECURITY (RLS) & PUBLIC READ/WRITE ACCESS
-- ========================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fuel_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Allow public and service role access for all tables
CREATE POLICY "Allow public read/write on users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write on fuel_prices" ON public.fuel_prices FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write on stations" ON public.stations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/write on orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);

-- ========================================================
-- SEED INITIAL FUELGO DATA
-- ========================================================

-- Seed Fuel Prices
INSERT INTO public.fuel_prices (fuel_type, price_per_unit, unit, change_pct) VALUES
  ('petrol', 94.72, 'L', 0.15),
  ('diesel', 87.62, 'L', -0.05),
  ('cng', 78.50, 'kg', 0.00),
  ('ev', 9.20, 'kWh', 0.00),
  ('premium', 112.00, 'L', 0.20),
  ('lpg', 68.00, 'kg', 0.00)
ON CONFLICT (fuel_type) DO UPDATE SET price_per_unit = EXCLUDED.price_per_unit;

-- Seed Stations in Chennai
INSERT INTO public.stations (name, emoji, city, lat, lng, rating, is_open, fuels_available, distance_km) VALUES
  ('Indian Oil', '⛽', 'Chennai', 13.0827, 80.2707, 4.9, true, '["petrol", "diesel"]'::jsonb, 1.2),
  ('BPCL', '🔵', 'Chennai', 13.0850, 80.2750, 4.8, true, '["petrol", "diesel"]'::jsonb, 2.5),
  ('HP', '⚡', 'Chennai', 13.0800, 80.2710, 4.7, true, '["petrol", "diesel", "cng"]'::jsonb, 3.1),
  ('Shell', '🐚', 'Chennai', 13.0900, 80.2800, 4.9, true, '["petrol", "diesel"]'::jsonb, 4.5),
  ('Tata Power EV', '⚡', 'Chennai', 13.0830, 80.2720, 4.6, true, '["ev"]'::jsonb, 2.0),
  ('Adani Gas', '🟡', 'Chennai', 13.0860, 80.2780, 4.5, true, '["cng"]'::jsonb, 3.5)
ON CONFLICT DO NOTHING;

-- Seed Sample Customer
INSERT INTO public.users (name, email, password_hash, phone) VALUES
  ('Priya Sharma', 'priya@example.com', '$2a$10$wO8l3q1F/yX0c.X0b1u3d.2v8Q2O5V3b5X7Y9Z1A3B5C7D9E1F3G5', '9876543210')
ON CONFLICT (email) DO NOTHING;
