import { FuelProduct, IndianCityRate, AssetVehicle, DeliveryAddress, BowserDriver, FuelOrder, UserProfile } from './types';

export const INDIAN_CITIES: IndianCityRate[] = [
  {
    cityName: 'Chennai',
    state: 'Tamil Nadu',
    dieselRate: 92.34,
    petrolRate: 100.75,
    biodieselRate: 86.50,
    evRate: 17.90,
    adblueRate: 46.00,
    lat: 13.0827,
    lng: 80.2707,
    activeBowsersCount: 24,
  },
  {
    cityName: 'Bengaluru',
    state: 'Karnataka',
    dieselRate: 88.94,
    petrolRate: 102.86,
    biodieselRate: 83.20,
    evRate: 17.50,
    adblueRate: 45.00,
    lat: 12.9716,
    lng: 77.5946,
    activeBowsersCount: 28,
  },
  {
    cityName: 'Mumbai',
    state: 'Maharashtra',
    dieselRate: 92.15,
    petrolRate: 104.21,
    biodieselRate: 86.40,
    evRate: 19.00,
    adblueRate: 46.50,
    lat: 19.0760,
    lng: 72.8777,
    activeBowsersCount: 42,
  },
  {
    cityName: 'Delhi NCR / Gurugram',
    state: 'Haryana / Delhi',
    dieselRate: 87.62,
    petrolRate: 94.72,
    biodieselRate: 81.90,
    evRate: 16.80,
    adblueRate: 42.00,
    lat: 28.4595,
    lng: 77.0266,
    activeBowsersCount: 36,
  },
  {
    cityName: 'Hyderabad',
    state: 'Telangana',
    dieselRate: 95.65,
    petrolRate: 107.41,
    biodieselRate: 89.10,
    evRate: 18.20,
    adblueRate: 44.50,
    lat: 17.3850,
    lng: 78.4867,
    activeBowsersCount: 22,
  },
  {
    cityName: 'Pune',
    state: 'Maharashtra',
    dieselRate: 90.45,
    petrolRate: 103.88,
    biodieselRate: 85.00,
    evRate: 18.50,
    adblueRate: 45.00,
    lat: 18.5204,
    lng: 73.8567,
    activeBowsersCount: 19,
  },
  {
    cityName: 'Kolkata',
    state: 'West Bengal',
    dieselRate: 90.76,
    petrolRate: 103.94,
    biodieselRate: 85.20,
    evRate: 18.00,
    adblueRate: 47.00,
    lat: 22.5726,
    lng: 88.3639,
    activeBowsersCount: 16,
  },
  {
    cityName: 'Ahmedabad',
    state: 'Gujarat',
    dieselRate: 90.10,
    petrolRate: 94.44,
    biodieselRate: 84.10,
    evRate: 16.50,
    adblueRate: 43.00,
    lat: 23.0225,
    lng: 72.5714,
    activeBowsersCount: 18,
  }
];

export const FUEL_PRODUCTS: FuelProduct[] = [
  {
    id: 'diesel_hsd',
    name: 'High-Speed Diesel (HSD BS-VI)',
    shortName: 'HSD Diesel',
    category: 'Liquid Fuel',
    description: 'Ultra-low sulfur (10 ppm) commercial grade diesel for DG sets, heavy transport fleets, and construction equipment with PESO quality seal.',
    pricePerUnit: 88.94,
    unit: 'Litre',
    octaneOrGrade: 'Cetane Index ≥51',
    color: 'emerald',
    accentBadge: 'B2B Favorite',
    minOrderQty: 50,
    maxOrderQty: 10000,
    iconName: 'Fuel',
    popularFor: 'Commercial DG Sets, Heavy Fleets & Construction'
  },
  {
    id: 'petrol_ms',
    name: 'Motor Spirit Petrol (Speed E20)',
    shortName: 'Petrol (MS)',
    category: 'Liquid Fuel',
    description: 'Premium octane motor spirit with detergency additives for company car fleets, executive sedans, and light transport vehicles.',
    pricePerUnit: 102.86,
    unit: 'Litre',
    octaneOrGrade: '91 Octane (E20)',
    color: 'amber',
    accentBadge: 'High Octane',
    minOrderQty: 20,
    maxOrderQty: 2000,
    iconName: 'Flame',
    popularFor: 'Passenger Fleets, Executive Vans & Bikes'
  },
  {
    id: 'biodiesel_b20',
    name: 'Clean Bio-Diesel (IS 15607 B20)',
    shortName: 'Bio-Diesel B20',
    category: 'Green Alternative',
    description: 'Eco-friendly 20% ester blend reducing particulate emissions by 34%. Ideal for ESG certified corporations and industrial parks.',
    pricePerUnit: 83.20,
    unit: 'Litre',
    octaneOrGrade: 'IS 15607 Certified',
    color: 'teal',
    accentBadge: 'ESG / Net Zero',
    minOrderQty: 100,
    maxOrderQty: 15000,
    iconName: 'Leaf',
    popularFor: 'Green Tech Parks, ESG Fleets & Mining'
  },
  {
    id: 'ev_charge',
    name: 'Mobile EV Fast Charging (120kW DC)',
    shortName: 'Mobile EV Fast-Charge',
    category: 'Clean Power',
    description: 'On-demand mobile battery truck with dual CCS2 guns delivering up to 120kW DC ultra-rapid charge directly to your parked EV.',
    pricePerUnit: 17.50,
    unit: 'kWh',
    octaneOrGrade: '120kW DC Fast',
    color: 'cyan',
    accentBadge: 'Zero Emission',
    minOrderQty: 20,
    maxOrderQty: 150,
    iconName: 'Zap',
    popularFor: 'EV Fleet Depots, Delivery 3W/4W, Gated Condos'
  },
  {
    id: 'adblue_def',
    name: 'AdBlue Diesel Exhaust Fluid (ISO 22241)',
    shortName: 'AdBlue (DEF)',
    category: 'Exhaust Fluid',
    description: 'Pure 32.5% aqueous urea solution required for BS-VI SCR catalytic converters in modern diesel trucks and heavy gensets.',
    pricePerUnit: 45.00,
    unit: 'Litre',
    octaneOrGrade: 'AUS 32 / ISO 22241',
    color: 'indigo',
    accentBadge: 'BS-VI Essential',
    minOrderQty: 20,
    maxOrderQty: 2000,
    iconName: 'Droplets',
    popularFor: 'Modern BS-VI Commercial Fleets & Gensets'
  }
];

export const INITIAL_SAVED_ADDRESSES: DeliveryAddress[] = [
  {
    id: 'addr-blr-01',
    label: 'Titan Logistics Hub (Main Yard)',
    streetAddress: 'Plot 44-B, EPIP Industrial Area, Near ITPL',
    area: 'Whitefield',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560066',
    lat: 12.9854,
    lng: 77.7289,
    landmark: 'Opposite SAP Labs Gate 2',
    siteContactPerson: 'Suresh Gowda (Yard Supervisor)',
    siteContactPhone: '+91 98450 12891',
    isGatedOrSecured: true,
    hasEarthingPoint: true,
  },
  {
    id: 'addr-blr-02',
    label: 'RMZ Ecoworld DG Plant Room 3',
    streetAddress: 'Outer Ring Road, Bellandur',
    area: 'Marathahalli-Sarjapur ORR',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560103',
    lat: 12.9242,
    lng: 77.6835,
    landmark: 'Behind Tower 6 Loading Dock',
    siteContactPerson: 'Vikas Sharma (Chief Facility Eng)',
    siteContactPhone: '+91 97312 44901',
    isGatedOrSecured: true,
    hasEarthingPoint: true,
  },
  {
    id: 'addr-blr-03',
    label: 'Prestige Lakeside Construction Site',
    streetAddress: 'Survey 102/1, Gunjur-Varthur Main Road',
    area: 'Varthur',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560087',
    lat: 12.9412,
    lng: 77.7314,
    landmark: 'Heavy Machinery Gate 3',
    siteContactPerson: 'Ramesh Reddy (Site Incharge)',
    siteContactPhone: '+91 99008 33412',
    isGatedOrSecured: true,
    hasEarthingPoint: true,
  }
];

export const INITIAL_ASSETS: AssetVehicle[] = [
  {
    id: 'asset-dg-01',
    name: 'Cummins QSK60-G4 2000 kVA DG Set',
    type: 'dg_genset',
    registrationNo: 'DG-BLR-RMZ-01',
    fuelType: 'diesel_hsd',
    tankCapacityL: 3000,
    currentFuelLevelPercent: 28,
    consumptionRatePerHour: 340,
    lastRefueledDate: '2026-08-10',
  },
  {
    id: 'asset-dg-02',
    name: 'Kirloskar 500 kVA Silent Genset',
    type: 'dg_genset',
    registrationNo: 'DG-TITAN-WH-02',
    fuelType: 'diesel_hsd',
    tankCapacityL: 900,
    currentFuelLevelPercent: 18,
    consumptionRatePerHour: 95,
    lastRefueledDate: '2026-08-12',
  },
  {
    id: 'asset-flt-01',
    name: 'Tata Signa 4825.TK Heavy Hauler (x6 Units)',
    type: 'fleet_truck',
    registrationNo: 'KA-51-AJ-9021',
    fuelType: 'diesel_hsd',
    tankCapacityL: 400,
    currentFuelLevelPercent: 42,
    consumptionRatePerHour: 28,
    lastRefueledDate: '2026-08-14',
  },
  {
    id: 'asset-exc-01',
    name: 'Komatsu PC210 Hydraulic Excavator',
    type: 'construction_heavy',
    registrationNo: 'EXC-PRST-88',
    fuelType: 'diesel_hsd',
    tankCapacityL: 400,
    currentFuelLevelPercent: 35,
    consumptionRatePerHour: 22,
    lastRefueledDate: '2026-08-13',
  },
  {
    id: 'asset-ev-01',
    name: 'Mahindra Zor Grand EV Delivery Fleet (x4)',
    type: 'passenger_car',
    registrationNo: 'KA-03-EV-1104',
    fuelType: 'ev_charge',
    tankCapacityL: 40,
    currentFuelLevelPercent: 15,
    consumptionRatePerHour: 8,
    lastRefueledDate: '2026-08-15',
  }
];

export const DEMO_BOWSERS: BowserDriver[] = [
  {
    id: 'bwsr-01',
    name: 'Pawan Teja',
    phone: '+91 98860 77123',
    photoUrl: '/pawan.jpg',
    rating: 4.94,
    tripsCompleted: 1420,
    bowserRegNo: 'KA-01-MF-8834',
    bowserCapacityLitres: 6000,
    currentFuelStockL: 4450,
    pesoLicenseNo: 'PESO/SC/KR/DL/2024/0981',
    speedKmh: 38,
    currentLat: 12.9650,
    currentLng: 77.6750,
    dispenserTempC: 28.4,
    isEarthingActive: true,
    sparkArrestorVerified: true,
  },
  {
    id: 'bwsr-02',
    name: 'Manjunath Gowda',
    phone: '+91 94480 33819',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    rating: 4.88,
    tripsCompleted: 980,
    bowserRegNo: 'KA-53-E-4412',
    bowserCapacityLitres: 4000,
    currentFuelStockL: 2800,
    pesoLicenseNo: 'PESO/SC/KR/DL/2023/1142',
    speedKmh: 42,
    currentLat: 12.9350,
    currentLng: 77.7150,
    dispenserTempC: 29.1,
    isEarthingActive: true,
    sparkArrestorVerified: true,
  }
];

export const DEMO_USER_B2B: UserProfile = {
  id: 'usr-b2b-01',
  name: 'Vikramaditya Singhania',
  email: 'vikram.singhania@indialogistics.co.in',
  phone: '+91 98200 45910',
  role: 'b2b_fleet',
  companyName: 'Apex Translog India Pvt Ltd',
  gstin: '29AAACA8821R1ZK',
  avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  walletBalance: 48500,
  creditLimit: 500000,
  creditUsed: 142800,
  savedAddresses: INITIAL_SAVED_ADDRESSES,
  savedAssets: INITIAL_ASSETS,
  isVerified: true,
  pesoSafetyCertified: true,
};

export const INITIAL_ORDERS: FuelOrder[] = [
  {
    id: 'ord-101',
    orderNumber: 'FG-IN-2026-8910',
    createdAt: '2026-08-16 21:15',
    scheduledTimeSlot: 'Express Delivery (Under 45 mins)',
    fuelType: 'diesel_hsd',
    quantity: 450,
    unitPrice: 88.94,
    fuelTotal: 40023,
    deliveryFee: 0,
    platformFee: 99,
    gstAmount: 7222,
    totalPayable: 47344,
    status: 'en_route',
    deliveryAddress: INITIAL_SAVED_ADDRESSES[0],
    asset: INITIAL_ASSETS[0],
    paymentMethod: 'credit_line',
    paymentStatus: 'credit_authorized',
    deliveryOtp: '7392',
    assignedBowser: DEMO_BOWSERS[0],
    flowRateLpm: 65,
    densityReport: {
      measuredDensity: 832.6,
      standardDensity: 830.0,
      temperature: 28.2,
      flashPoint: '> 38.5°C'
    },
    pesoSealNumber: 'PESO-SEAL-KA-99128'
  },
  {
    id: 'ord-102',
    orderNumber: 'FG-IN-2026-8845',
    createdAt: '2026-08-15 14:30',
    scheduledTimeSlot: 'Completed',
    fuelType: 'diesel_hsd',
    quantity: 800,
    unitPrice: 88.94,
    fuelTotal: 71152,
    deliveryFee: 0,
    platformFee: 99,
    gstAmount: 12825,
    totalPayable: 84076,
    status: 'completed',
    deliveryAddress: INITIAL_SAVED_ADDRESSES[1],
    asset: INITIAL_ASSETS[1],
    paymentMethod: 'upi',
    paymentStatus: 'paid',
    deliveryOtp: '5190',
    dispensedQty: 800.4,
    dispensedStartedAt: '2026-08-15 15:40',
    dispensedCompletedAt: '2026-08-15 16:02',
    assignedBowser: DEMO_BOWSERS[1],
    densityReport: {
      measuredDensity: 831.9,
      standardDensity: 830.0,
      temperature: 29.0,
      flashPoint: '> 38.0°C'
    },
    pesoSealNumber: 'PESO-SEAL-KA-88741'
  }
];
